implemented
projdysvit/book-store pull request #11
Opened 2024-03-06 16:37 UTC by projdysvit

2024-03-06 18:50 UTC, olekskov requested changes

2024-03-06 18:50 UTC, olekskov commented on src/main/java/com/book/store/bookstore/service/impl/ShoppingCartServiceImpl.java
> +        return shoppingCartMapper.toDto(getShoppingCartByUserId(userId));
this code will lead to duplicates
e.g. 
cart already have cartItem for book with id 1L in quantity 5
on next request for new cartItem for book with id 1L it will create new item (with quantity 2 for example)

More expected behaviour is to make one item with quantity 7 instead

2024-03-06 18:50 UTC, olekskov commented on src/main/java/com/book/store/bookstore/service/impl/ShoppingCartServiceImpl.java
> +            throw new ShoppingCartForbiddenException("Not your's shopping cart");
Please make exception more generic, like EntityNotFoundException but for access.
This is not the last case where you should check user and he may try to access some entity that doesn't belong to him. Better to have common exception for such case

OR

Just use repository method that filter by both userId and cartItemId and just return 404 if user doesn't have such item

2024-03-07 11:00 UTC, kozhukhovsky approved these changes

2024-03-07 11:21 UTC, merged