created dtos and mappers, book controller and EntityNotFoundException…
projdysvit/book-store pull request #2
Opened 2024-02-22 15:01 UTC by projdysvit

…; added findById to book's service and repository.

2024-02-23 17:50 UTC, okuzan requested changes

2024-02-23 17:50 UTC, okuzan commented on src/main/java/com/book/store/bookstore/controller/BookController.java
> +    @PostMapping("/api/books")
make api project wide url prefix - it can be done in application properties
extract book - common part for all of these methods to controller level

2024-02-23 17:50 UTC, okuzan commented on src/main/java/com/book/store/bookstore/dto/mapper/impl/BookDtoMapper.java
> +                    .isbn(dto.getIsbn())
don't do it manually, use mapstruct

2024-02-24 16:28 UTC, olekskov approved these changes

2024-02-24 19:38 UTC, merged