F 7
projdysvit/book-store pull request #7
Opened 2024-02-29 15:16 UTC by projdysvit

2024-02-29 19:19 UTC, okuzan requested changes
f-7 is a bad name for a feature-branch, if only F7 isn't an issue id in some project tracker

2024-02-29 19:19 UTC, okuzan commented on src/main/java/com/book/store/bookstore/service/impl/UserServiceImpl.java
> +            throw new RegistrationException("User with that email is exists");
```suggestion
            throw new RegistrationException("User with that email already exists: " + requestDto.getEmail());
```

2024-02-29 19:19 UTC, okuzan commented on src/main/java/com/book/store/bookstore/dto/request/user/UserRegistrationRequestDto.java
> +public class UserRegistrationRequestDto {
let's keep your codebase uniform and use records for DTO everywhere

2024-03-01 11:32 UTC, kozhukhovsky approved these changes

2024-03-01 11:37 UTC, merged